# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  path_filters:
    - "!libinjection-rs/data/sqli_keywords.txt"
    - "!**/Cargo.lock"
    - "!**/target/**"
    - "!**/generated/**"
    - "!**/@generated/**"
    - "!**/__generated__/**"
    - "!**/__generated/**"
    - "!**/_generated/**"
    - "!**/gen/**"
    - "!**/@gen/**"
    - "!**/__gen__/**"
    - "!**/__gen/**"
    - "!**/_gen/**"
