/*
Copyright Coraza Kubernetes Operator contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//! Byte-level helpers ported from `sqli_helpers.go`.

use super::consts::{BYTE_DOUBLE, BYTE_NULL, BYTE_SINGLE, FLAG_QUOTE_DOUBLE, FLAG_QUOTE_SINGLE};

/// Go `flag2Delimiter`.
pub(crate) fn flag2_delimiter(flags: u32) -> u8 {
    if (flags & FLAG_QUOTE_SINGLE) != 0 {
        BYTE_SINGLE
    } else if (flags & FLAG_QUOTE_DOUBLE) != 0 {
        BYTE_DOUBLE
    } else {
        BYTE_NULL
    }
}

/// Go `isBackslashEscaped`: odd number of trailing backslashes → escaped.
pub(crate) fn is_backslash_escaped(s: &[u8]) -> bool {
    let mut count = 0_usize;
    for &b in s.iter().rev() {
        if b == b'\\' {
            count += 1;
        } else {
            break;
        }
    }
    !count.is_multiple_of(2)
}

/// Go `isDoubleDelimiterEscaped`.
pub(crate) fn is_double_delimiter_escaped(s: &[u8]) -> bool {
    s.first().zip(s.get(1)).is_some_and(|(a, b)| a == b)
}

/// Go `isByteWhite`.
pub(crate) fn is_byte_white(ch: u8) -> bool {
    matches!(ch, b' ' | b'\t' | b'\n' | 0x0b | b'\x0c' | b'\r' | 0xa0 | 0x00)
}

/// Go `strLenSpn`: longest prefix of `s[..length]` that contains only bytes in `accept`.
pub(crate) fn str_len_spn(s: &[u8], length: usize, accept: &[u8]) -> usize {
    let len = length.min(s.len());
    for (i, &b) in s.iter().enumerate().take(len) {
        if !accept.contains(&b) {
            return i;
        }
    }
    len
}

/// Go `strLenCSpn`: position of first byte where `accept_table[byte] == 1`.
///
/// `accept_table` is a 256-byte LUT: `1` = stop, `0` = continue.
pub(crate) fn str_len_cspn(s: &[u8], length: usize, accept_table: &[u8; 256]) -> usize {
    let len = length.min(s.len());
    for (i, &b) in s.iter().enumerate().take(len) {
        if accept_table.get(b as usize).copied().unwrap_or(0) == 1 {
            return i;
        }
    }
    len
}

/// Go `toUpperCmp`: case-insensitive compare where `expected_upper` is already uppercase.
pub(crate) fn to_upper_cmp(expected_upper: &[u8], s: &[u8]) -> bool {
    if expected_upper.len() != s.len() {
        return false;
    }
    expected_upper
        .iter()
        .zip(s.iter())
        .all(|(&e, &c)| e == c.to_ascii_uppercase())
}

/// Go `isMysqlComment`: is `input[pos..pos+3]` a `MySQL` conditional comment (`/*!`)?
pub(crate) fn is_mysql_comment(input: &[u8], pos: usize) -> bool {
    input.get(pos + 2).copied() == Some(b'!')
}

// Accept tables generated by build.rs (avoids const fn indexing limitations).
include!(concat!(env!("OUT_DIR"), "/accept_tables.rs"));
